permission:
    tpa: "essentials.tpa" # The permission for running the tpa command
    tpahere: "essentials.tpahere" # The permission for running the tpahere command

## Placeholders
#    %player% = The player that ran the /tpa command
#    %accept% = The clickable text to accept the request
#    %deny% = The clickable text to deny the request
message:
    spacer: "bar" # If this is 'bar' then it uses a long horizontal bar, if not then it uses the value as the spacer. Leave empty for no spacer.
    line: "&6Click %accept% &6or %deny%" # The message to send to the player
    accept: "&aAccept" # The text of the %accept% placeholder
    deny: "&cDeny" # The text of the %deny% placeholder
    use-display-name: true # If true use the display name rather than the real name for the %player% placeholder
